# Generated by Django 6.0.4 on 2026-05-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitas', models.TextField(verbose_name='Deskripsi Aktivitas')),
                ('tipe', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10, verbose_name='Tipe')),
                ('waktu', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catatan_sistem', to=settings.AUTH_USER_MODEL, verbose_name='Aktor / User')),
            ],
            options={
                'verbose_name': 'Catatan Sistem',
                'verbose_name_plural': 'Catatan Sistem',
                'ordering': ['-waktu'],
            },
        ),
    ]
