# Generated by Django 6.0.4 on 2026-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_firebase_uid_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_telp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='universitas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
