# Generated by Django 6.0.4 on 2026-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_color',
            field=models.CharField(blank=True, default='#E6F7FF', max_length=7),
        ),
    ]
