# Generated by Django 6.0.4 on 2026-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_color',
        ),
        migrations.AddField(
            model_name='customuser',
            name='banner_color',
            field=models.CharField(blank=True, help_text='Kode warna hex untuk banner profil, misal #00bfff', max_length=7, null=True),
        ),
    ]
