# Generated by Django 6.0.4 on 2026-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_profile_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
