# Generated by Django 6.0.4 on 2026-05-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_banner_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=30, unique=True, verbose_name='NIK')),
                ('asal_kampus', models.CharField(max_length=200, verbose_name='Asal Kampus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Peserta',
                'verbose_name_plural': 'Profil Peserta',
            },
        ),
    ]
