# Generated by Django 6.0.4 on 2026-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Pengguna', 'verbose_name_plural': 'Pengguna'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jabatan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit_kerja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit Kerja'),
        ),
    ]
