# Generated by Django 6.0.4 on 2026-05-19 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_options_customuser_jabatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('aktivitas', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('SYSTEM', 'SYSTEM'), ('LOGIN', 'LOGIN')], max_length=20)),
                ('aktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
    ]
