# Generated by Django 6.0.4 on 2026-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_logaktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wajib_ganti_sandi',
            field=models.BooleanField(default=True),
        ),
    ]
