# Generated by Django 6.0.4 on 2026-05-25 12:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    MasterUniversitas = apps.get_model('accounts', 'MasterUniversitas')
    MasterJurusan = apps.get_model('accounts', 'MasterJurusan')
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Profil = apps.get_model('accounts', 'Profil')

    # Migrate CustomUser
    for user in CustomUser.objects.all():
        if hasattr(user, 'universitas_old') and user.universitas_old:
            nama_univ = user.universitas_old.strip()
            if nama_univ:
                univ_obj, _ = MasterUniversitas.objects.get_or_create(nama=nama_univ)
                user.universitas = univ_obj
        if hasattr(user, 'jurusan_old') and user.jurusan_old:
            nama_jur = user.jurusan_old.strip()
            if nama_jur:
                jur_obj, _ = MasterJurusan.objects.get_or_create(nama=nama_jur)
                user.jurusan = jur_obj
        user.save()

    # Migrate Profil
    for profil in Profil.objects.all():
        if hasattr(profil, 'asal_kampus_old'):
            nama_kampus = (profil.asal_kampus_old or "").strip()
            if not nama_kampus:
                nama_kampus = "Belum Ditentukan"
            univ_obj, _ = MasterUniversitas.objects.get_or_create(nama=nama_kampus)
            profil.asal_kampus = univ_obj
            profil.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True, verbose_name='Nama Jurusan')),
                ('kode_jurusan', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Master Jurusan',
                'verbose_name_plural': 'Master Jurusan',
            },
        ),
        migrations.CreateModel(
            name='MasterUniversitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True, verbose_name='Nama Universitas')),
                ('kode_kemendikbud', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Universitas',
                'verbose_name_plural': 'Master Universitas',
            },
        ),
        # Rename old CharFields
        migrations.RenameField(
            model_name='customuser',
            old_name='universitas',
            new_name='universitas_old',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='jurusan',
            new_name='jurusan_old',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='asal_kampus',
            new_name='asal_kampus_old',
        ),
        # Add new ForeignKeys (allowing null=True temporarily)
        migrations.AddField(
            model_name='customuser',
            name='universitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.masteruniversitas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.masterjurusan'),
        ),
        migrations.AddField(
            model_name='profil',
            name='asal_kampus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.masteruniversitas', verbose_name='Asal Kampus'),
        ),
        # Run Python code to migrate the data
        migrations.RunPython(migrate_data),
        # Remove old CharFields
        migrations.RemoveField(
            model_name='customuser',
            name='universitas_old',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='jurusan_old',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='asal_kampus_old',
        ),
        # Set null=False on Profil.asal_kampus
        migrations.AlterField(
            model_name='profil',
            name='asal_kampus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.masteruniversitas', verbose_name='Asal Kampus'),
        ),
    ]
