# Generated by Django 6.0.4 on 2026-05-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profil'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertifikat',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikat'},
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sertifikats', to='accounts.profil', verbose_name='Profil Peserta'),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='file_sertifikat',
            field=models.FileField(upload_to='certificates/', verbose_name='File Dokumen'),
        ),
    ]
