# Generated by Django 6.0.4 on 2026-05-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_sertifikat_options_sertifikat_profil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertifikat',
            name='profil',
        ),
    ]
