"""
Django settings for sim_magang_portofolio project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
GOOGLE_CAPTCHA_SECRET_KEY = os.getenv('GOOGLE_CAPTCHA_SECRET_KEY')
GOOGLE_CAPTCHA_SITE_KEY = os.getenv('GOOGLE_CAPTCHA_SITE_KEY')
FIREBASE_KEY = os.getenv('FIREBASE_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ec6)4&5ais9^b@1y(!(*pxz+_a^gbzd26-o9d-o3412nk97zme')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

import socket

def get_local_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # Menghubungkan ke IP eksternal publik (tidak mengirimkan data) untuk menentukan interface mana yang aktif
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    except Exception:
        try:
            ip = socket.gethostbyname(socket.gethostname())
        except Exception:
            ip = '127.0.0.1'
    finally:
        s.close()
    return ip

LOCAL_IP = get_local_ip()

# Mengizinkan semua host untuk mempermudah pengembangan lokal, akses Wi-Fi, hotspot, dan tunneling (ngrok/pinggy)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# 
    'tailwind',
    'theme',
    'accounts',
    'logbook',
    'portfolio',
    'documents',
    'admin_panel',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.AuthenticationSecurityMiddleware',  # Pengamanan Otomatis Global Peran & Login
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sim_magang_portofolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sim_magang_portofolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'db_sim_mpp'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

X_FRAME_OPTIONS = 'SAMEORIGIN'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
INTERNAL_IPS = ["127.0.0.1"]

# Konfigurasi Tailwind
TAILWIND_APP_NAME = 'theme'
AUTH_USER_MODEL = 'accounts.CustomUser'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme/static'),
    os.path.join(BASE_DIR, 'static'),
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── Firebase Admin SDK ───────────────────────────────────────
import firebase_admin
from firebase_admin import credentials

FIREBASE_JSON_PATH = os.path.join(BASE_DIR, 'sim_magang_portofolio', 'firebase_credentials.json')

if not firebase_admin._apps:
    cred = credentials.Certificate(FIREBASE_JSON_PATH)
    firebase_admin.initialize_app(cred)

# ── Firebase Web Config (digunakan di template) ─────────────
FIREBASE_WEB_CONFIG = {
    'apiKey': FIREBASE_KEY,
    'authDomain': 'sim-mpp-43dfe.firebaseapp.com',
    'projectId': 'sim-mpp-43dfe',
    'storageBucket': 'sim-mpp-43dfe.firebasestorage.app',
    'messagingSenderId': '228351938195',
    'appId': '1:228351938195:web:1c8420f8a97c901c0cc766',
}
RECAPTCHA_V3_SITE_KEY = '6LdElu0sAAAAAE8XLxKELrkH8L27WFgTrAVfJHuy'

# ── Google reCAPTCHA v2 Keys ──
# Gunakan kunci dari environment (.env) jika dikonfigurasi, jika tidak gunakan Kunci Pengujian resmi Google
GOOGLE_CAPTCHA_V2_SITE_KEY = GOOGLE_CAPTCHA_SITE_KEY
if not GOOGLE_CAPTCHA_V2_SITE_KEY or not GOOGLE_CAPTCHA_SECRET_KEY:
    GOOGLE_CAPTCHA_V2_SITE_KEY = '6LeIxAcTAAAAAJcZVRqyhH71UMIEGNQ_MXjiZKhI'
    GOOGLE_CAPTCHA_SECRET_KEY = '6LeIxAcTAAAAAGG-vFI1qg6A2yRnZs5ahpQNxyga'

LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'wawansuwandi529@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'shvxbqlvtdclwdkp')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ── Kebijakan Sesi & Keamanan Bank-Grade ────────────────────────
# Sesi secara otomatis terhapus saat user menutup browser tab/window
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Masa aktif cookie login maksimal 1 jam (3600 detik) jika didiamkan tanpa aktifitas
SESSION_COOKIE_AGE = 3600
# Sesi diperbarui setiap kali user berinteraksi dengan server agar tidak cepat habis di tengah kerja
SESSION_SAVE_EVERY_REQUEST = True