# Generated by Django 6.0.5 on 2026-05-06 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('detail_pekerjaan', models.TextField()),
                ('tautan_pendukung', models.URLField(blank=True, max_length=500, null=True)),
                ('lampiran_gambar', models.ImageField(blank=True, null=True, upload_to='logbook/images/')),
                ('lampiran_dokumen', models.FileField(blank=True, null=True, upload_to='logbook/docs/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('REVISI', 'Revisi'), ('DISETUJUI', 'Disetujui')], default='MENUNGGU', max_length=10)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tugas', models.CharField(max_length=255)),
                ('pembimbing', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELESAI', 'Selesai')], default='PENDING', max_length=10)),
                ('deskripsi_tugas', models.TextField(blank=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
