# Generated by Django 6.0.4 on 2026-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='keterangan',
            field=models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN_PERKULIAHAN', 'Izin Perkuliahan'), ('WFH', 'WFH')], default='HADIR', max_length=20),
        ),
    ]
