# Generated by Django 6.0.4 on 2026-05-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_logbook_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='judul',
            field=models.CharField(default='Logbook Harian', max_length=255),
        ),
    ]
