# Generated by Django 6.0.4 on 2026-05-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profil'),
        ('logbook', '0003_logbook_judul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbook',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Logbook', 'verbose_name_plural': 'Logbook'},
        ),
        migrations.AlterModelOptions(
            name='tugas',
            options={'verbose_name': 'Tugas', 'verbose_name_plural': 'Tugas'},
        ),
        migrations.AddField(
            model_name='logbook',
            name='kegiatan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kegiatan'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='komentar_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Komentar Admin'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbooks', to='accounts.profil', verbose_name='Profil Peserta'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_list', to='accounts.profil', verbose_name='Profil Peserta'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='detail_pekerjaan',
            field=models.TextField(verbose_name='Uraian'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deadline',
            field=models.DateField(verbose_name='Batas Waktu'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deskripsi_tugas',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='judul_tugas',
            field=models.CharField(max_length=255, verbose_name='Judul'),
        ),
    ]
