# Generated by Django 6.0.4 on 2026-05-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_alter_logbook_options_alter_tugas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='kegiatan',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='komentar_admin',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='tugas',
            name='profil',
        ),
    ]
