# Generated by Django 6.0.4 on 2026-05-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_remove_logbook_kegiatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='keterangan_file',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
