# Generated by Django 6.0.4 on 2026-05-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_logbook_keterangan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='file_pembimbing',
            field=models.FileField(blank=True, null=True, upload_to='logbook/pembimbing/'),
        ),
    ]
