# Generated by Django 6.0.5 on 2026-05-06 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_proyek', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('teknologi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar_sampul', models.ImageField(upload_to='portfolio/covers/')),
                ('tautan_repository', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
