# Generated by Django 6.0.4 on 2026-05-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profil'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portofolio', 'verbose_name_plural': 'Portofolio'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file_proyek',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', verbose_name='File Proyek'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='accounts.profil', verbose_name='Profil Peserta'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='judul_proyek',
            field=models.CharField(max_length=255, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tautan_repository',
            field=models.URLField(blank=True, null=True, verbose_name='Tautan / File Proyek'),
        ),
    ]
