# Generated by Django 6.0.4 on 2026-05-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_portfolio_file_proyek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='profil',
        ),
    ]
