# Generated by Django 6.0.4 on 2026-05-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='file_proyek',
        ),
    ]
