# Generated by Django 6.0.4 on 2026-05-25 12:15

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_data(apps, schema_editor):
    MasterKategori = apps.get_model('portfolio', 'MasterKategori')
    Portfolio = apps.get_model('portfolio', 'Portfolio')

    for pf in Portfolio.objects.all():
        if hasattr(pf, 'kategori_old'):
            nama_kat = (pf.kategori_old or "").strip()
            if not nama_kat:
                nama_kat = "Lainnya"
            slug = slugify(nama_kat)
            
            # Ensure slug uniqueness in data migration
            orig_slug = slug
            counter = 1
            while MasterKategori.objects.filter(slug=slug).exclude(nama=nama_kat).exists():
                slug = f"{orig_slug}-{counter}"
                counter += 1

            kat_obj, _ = MasterKategori.objects.get_or_create(
                nama=nama_kat,
                defaults={'slug': slug}
            )
            pf.kategori = kat_obj
            pf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_file_proyek'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Master Kategori',
                'verbose_name_plural': 'Master Kategori',
            },
        ),
        # Rename old CharField
        migrations.RenameField(
            model_name='portfolio',
            old_name='kategori',
            new_name='kategori_old',
        ),
        # Add new ForeignKey (allowing null=True temporarily)
        migrations.AddField(
            model_name='portfolio',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.masterkategori', verbose_name='Kategori'),
        ),
        # Run Python code to migrate the data
        migrations.RunPython(migrate_data),
        # Remove old CharField
        migrations.RemoveField(
            model_name='portfolio',
            name='kategori_old',
        ),
        # Alter field to set null=False
        migrations.AlterField(
            model_name='portfolio',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.masterkategori', verbose_name='Kategori'),
        ),
    ]
