# Generated by Django 6.0.4 on 2026-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_masterkategori_alter_portfolio_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='database',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Database'),
        ),
    ]
